### PR TITLE
Add GDG Toledo picture

### PR DESCRIPTION
**Pull request by mdelapenya**
Not sure how to add group metadata: twitter handle, meetup...

Any help here?

### CODE REVIEW

**Comment by abdonrd** [comment]
The metadata is on Firebase. Give the details and I can update it! 😄 

```json
{
  "city" : "Toledo",
  "facebook" : "",
  "googlePlus" : "",
  "meetup" : "https://www.meetup.com/GDGToledo_ES",
  "name" : "GDG Toledo",
  "twitter" : "http://www.twitter.com/GDGToledo_ES"
}

```

**Review by abdonrd — CHANGES_REQUESTED** [review]
Please, crop the image to `600x392`, as the other images.

**Comment by mdelapenya** [comment]
Image updated (push forced).

Here you have the metadata (no Facebook nor G+)
```
{
  "city" : "Toledo",
  "facebook" : "",
  "googlePlus" : "",
  "meetup" : "https://www.meetup.com/GDGToledo_ES",
  "name" : "GDG Toledo",
  "twitter" : "http://www.twitter.com/GDGToledo_ES"
}
```
Thanks!

**Review by abdonrd — APPROVED** [review]
Thanks!

**Comment by abdonrd** [comment]
Deployed! :)

screen shot 2018-06-12 at 14 33 41

**Comment by mdelapenya** [comment]
image

**Pull request merged**
