### PR TITLE
Split tasks in multiple files

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by iblancasa** [comment]
What do you think about adding lint-css?

**Comment by abdonrd** [comment]
With which tool?

**Comment by iblancasa** [comment]
With "gulp-csslint". If you want I can do it

**Comment by abdonrd** [comment]
Check if it is compatible with Polymer custom properties and mixins.

**Comment by iblancasa** [comment]
Ok!

**Comment by iblancasa** [comment]
Oh...! Mixins are not supported

**Comment by abdonrd** [comment]
Then... no :(

**Pull request merged**
