### PR TITLE
Adding help to gulp

### PR DESCRIPTION
**Pull request by iblancasa**
It is only for know what is the mission of each task

### CODE REVIEW

**Comment by abdonrd** [comment]
Thanks for the PR, @iblancasa! :tada: 

Fix the lint error and LGTM. :)

screen shot 2016-04-06 at 20 50 49

**Comment by iblancasa** [comment]
Solved!
Sorry, I didn't see it

**Comment by abdonrd** [comment]
Squash the commits, please. :sweat_smile: 

PS: Hum, I think that we can add the `gulp lint` task in Travis.

**Comment by abdonrd** [comment]
Thanks! :)

**Pull request merged**
